stages:
  data_visualizacion:
    cmd: python src/data_visualizacion.py
    deps:
      - src/data_visualizacion.py
      - data/raw/datos_creditos.csv
      - data/raw/datos_tarjetas.csv
    outs:
      - docs/figures/distribucion_target.png
      - docs/figures/correlacion_heatmap_creditos.png
      - docs/figures/correlacion_heatmap_tarjetas.png
      - docs/figures/boxplot_variable_numerica_vs_target.png
      - docs/figures/heatmap_valores_nulos_creditos.png
      - docs/reports/reporte_eda_creditos.html
      - docs/reports/reporte_eda_tarjetas.html

  test_pandera:
    cmd: pytest --html=docs/report_basico.html --self-contained-html test/test_data_quality.py -v ||true
    deps:
      - data/raw/datos_creditos.csv
      - data/raw/datos_tarjetas.csv
      - test/test_data_quality.py
    outs:
      - docs/report_basico.html

  test_ge:
    cmd: pytest --html=docs/report_ge.html --self-contained-html test/test_data_quality_ge.py -v ||true
    deps:
      - data/raw/datos_creditos.csv
      - data/raw/datos_tarjetas.csv
      - test/test_data_quality_ge.py
    outs:
      - docs/report_ge.html

  data_processing:
    cmd: python src/data_prep.py
    deps:
      - src/data_prep.py
      - data/raw/datos_creditos.csv
      - data/raw/datos_tarjetas.csv
    outs:
      - docs/processed/datos_integrados.csv
      - docs/processed/metadata_datos_integrados.txt
  
    train_model:
      cmd: python src/train_model.py
      deps:
        - src/train_model.py
        - docs/processed/datos_integrados.csv
        - docs/processed/metadata_datos_integrados.txt
      outs:
        - docs/models/best_model.pkl
        - docs/models/prod_preprocessor.pkl
        - docs/figures/confusion_matrix.png
      metrics:
        - docs/metrics/train_metrics.json